library(shiny)
library(rCharts)
load("data.RData")

shinyServer(function(input, output) {
  output$q1 <- renderChart({
    q1 <- rCharts:::Highcharts$new()
    q1$chart(zoomType = "xy", type = 'bar')
    q1$xAxis(categories = q1_results$Name, title = list(text="Authors"))
    q1$title(text="Most Published Authors")
    q1$series(data = q1_results$Long_Score, name = "Longevity Score (years)", legendIndex = 2 )
    q1$series(data = q1_results$Count, name = "Publication Count", legendIndex = 1)
    q1$addParams(dom = 'q1')
    return(q1)
  })
  output$q2 <- renderChart({
    q2 <- rCharts:::Highcharts$new()
    q2$chart(zoomType = "xy", type = 'bar')
    q2$xAxis(categories = q2_results$Name, title = list(text="Authors"))
    q2$title(text="Rising Stars Authors")
    q2$series(data = q2_results$Long_Score, name = "Longevity Score (years)", legendIndex = 2 )
    q2$series(data = q2_results$Count, name = "Publication Count", legendIndex = 1)
    q2$addParams(dom = 'q2')
    return(q2)
  })
  output$q3 <- renderChart({
    q3 <- rCharts:::Highcharts$new()
    q3$chart(zoomType = "xy", type = 'bar')
    q3$xAxis(categories = q3_results$Name, title = list(text="Authors"))
    q3$yAxis(title = list(text = "Score"))
    q3$title(text="Most Socialble Authors")
    q3$series(data = q3_results$Social_Score, name = "Socialbility Score")
    q3$addParams(dom = 'q3')
    return(q3)
    
  })
  output$q4 <- renderChart({
    q4 <- rCharts:::Highcharts$new()
    q4$chart(zoomType = "xy", type = 'bar')
    q4$xAxis(categories = q4_results$Journal, title = list(text="Authors"))
    q4$yAxis(title = list(text = "Avg. Citations per Paper"))
    q4$title(text="Top Journals Based on Avg Citations")
    q4$series(data = q4_results$avg_cits, name = "Avg. Citations")
    q4$addParams(dom = 'q4')
    return(q4)
  })
})
